services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    image: asha-store:dev-v1
    env_file:
      - ./api/.env.development
    environment:
      PORT: ${PORT}
    expose:
      - ${PORT}
    volumes:
      - ./api:/app
      - /app/node_modules
