x-default-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "30M"
    max-file: "3"

services:
  api:
    image: ghcr.io/anamulhaque22/shop-compose:latest
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp
    environment:
      PORT: ${PORT}
    deploy:
      resources:
        limits:
          memory: "1G"
          cpus: "1.0"
        reservations:
          memory: "512M"
          cpus: "0.5"
    logging: *default-logging
    expose:
      - ${PORT}

  shop-db:
    logging: *default-logging
    expose:
      - ${POSTGRES_PORT}
  redis:
    logging: *default-logging
    expose:
      - ${REDIS_PORT}

  nginx:
    logging: *default-logging
