
FROM node:22-alpine

ARG NODE_ENVIRONMENT
ARG PNPM_VERSION

WORKDIR /app

RUN npm install -g pnpm@${PNPM_VERSION}

COPY package.json pnpm-lock.yaml ./
RUN --mount=type=cache,target=/root/.pnpm/store \
    pnpm install --frozen-lockfile

COPY . .

USER node

EXPOSE 3000

CMD ["pnpm","run","start:dev"]