FROM node:22-alpine

ARG PNPM_VERSION
ARG NODE_ENV=development

WORKDIR /app

RUN npm install -g pnpm@${PNPM_VERSION}

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 3000

CMD ["pnpm","run","start:dev"]