# syntax=docker/dockerfile:1
FROM node:22-alpine AS builder

ARG PNPM_VERSION

WORKDIR /app

RUN npm install -g pnpm@${PNPM_VERSION}

COPY package.json pnpm-lock.yaml ./
RUN --mount=type=cache,target=/root/.pnpm/store \
    pnpm install --frozen-lockfile

COPY . .

RUN pnpm run build

FROM node:22-alpine AS production

ARG PNPM_VERSION

WORKDIR /app

RUN npm install -g pnpm@${PNPM_VERSION}

COPY package.json pnpm-lock.yaml ./
RUN --mount=type=cache,target=/root/.pnpm/store \
    pnpm install --frozen-lockfile --prod

COPY --from=builder /app/dist ./dist

USER node

EXPOSE 3000

CMD ["pnpm","run","start:prod"]
