name: CI Practice Pipeline

on:
  push:
    branches: [test]
  pull_request:
    branches: [test]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nodejs
        uses: actions/setup-node@v7
        with:
          node-version: "22"

      - name: Install pnpm
        run: npm install -g pnpm@9.12.0

      - name: Install dependencies
        working-directory: ./api
        run: pnpm install --frozen-lockfile

      - name: Run test
        working-directory: ./api
        run: pnpm run test
