name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm + Node
        uses: pnpm/setup@v1
        with:
          version: 9
          runtime: node@22
          # cache: true
          cache-dependency-path: api/pnpm-lock.yaml
          install: false

      - name: Install dependencies
        working-directory: ./api
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test
        working-directory: ./api
        env:
          NODE_ENV: test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm + Node
        uses: pnpm/setup@v1
        with:
          version: 9
          runtime: node@22
          # cache: true
          cache-dependency-path: api/pnpm-lock.yaml
          install: false

      - name: Install dependencies
        working-directory: ./api
        run: pnpm install --frozen-lockfile

      - name: Run lint
        working-directory: ./api
        run: pnpm run lint

  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm + Node
        uses: pnpm/setup@v1
        with:
          version: 9
          runtime: node@22
          # cache: true
          cache-dependency-path: api/pnpm-lock.yaml
          install: false

      - name: Check pnpm version
        run: "echo pnpm version: $(pnpm --version)"

      - name: Install dependencies
        working-directory: ./api
        run: pnpm install --frozen-lockfile

      - name: Run type check
        working-directory: ./api
        run: pnpm run type-check
